#include "config.h"

#include <glib.h>
#include <glib/gstdio.h>

#include "cc-hypridle.h"

static gchar *
get_config_path (void)
{
  return g_build_filename (g_get_user_config_dir (), "hypr", "hypridle.conf", NULL);
}

CcHypridleConfig *
cc_hypridle_config_new (void)
{
  return g_new0 (CcHypridleConfig, 1);
}

void
cc_hypridle_config_free (CcHypridleConfig *config)
{
  if (!config)
    return;

  for (gsize i = 0; i < config->n_rules; i++)
    {
      g_free (config->rules[i].timeout);
      g_free (config->rules[i].action);
    }
  g_free (config->rules);
  g_free (config);
}

gboolean
cc_hypridle_config_load (CcHypridleConfig *config, GError **error)
{
  g_autofree gchar *path = get_config_path ();
  g_autofree gchar *contents = NULL;
  gsize len;
  gchar **lines;

  if (!g_file_test (path, G_FILE_TEST_EXISTS))
    return TRUE;

  if (!g_file_get_contents (path, &contents, &len, error))
    return FALSE;

  lines = g_strsplit (contents, "\n", -1);
  if (!lines)
    return TRUE;

  gsize count = g_strv_length (lines);
  gsize rule_count = 0;

  for (gsize i = 0; i < count; i++)
    {
      gchar *line = g_strstrip (lines[i]);

      if (line[0] == '\0' || line[0] == '#')
        continue;

      if (g_str_has_prefix (line, "timeout = "))
        {
          config->rules = g_renew (CcHypridleRule, config->rules, rule_count + 1);

          g_auto (GStrv) parts = g_strsplit (line + 10, " ", 2);
          if (parts && parts[0])
            {
              config->rules[rule_count].timeout = g_strdup (parts[0]);
              config->rules[rule_count].action = parts[1] ? g_strdup (parts[1]) : NULL;
              rule_count++;
            }
        }
    }

  config->n_rules = rule_count;
  g_strfreev (lines);

  return TRUE;
}

gboolean
cc_hypridle_config_save (CcHypridleConfig *config, GError **error)
{
  g_autofree gchar *path = get_config_path ();
  GString *contents;

  contents = g_string_new ("# Generated by hypr-control-center\n\n");

  if (!g_file_test (path, G_FILE_TEST_EXISTS))
    {
      g_autofree gchar *dir = g_path_get_dirname (path);
      g_mkdir_with_parents (dir, 0755);
    }

  for (gsize i = 0; i < config->n_rules; i++)
    {
      g_string_append_printf (contents, "timeout = %s", config->rules[i].timeout);
      if (config->rules[i].action)
        g_string_append_printf (contents, " %s", config->rules[i].action);
      g_string_append_c (contents, '\n');
    }

  gboolean ret = g_file_set_contents (path, contents->str, -1, error);
  g_string_free (contents, TRUE);

  return ret;
}

gboolean
cc_hypridle_config_set_idle (CcHypridleConfig *config,
                             guint             timeout_secs,
                             const gchar      *action)
{
  for (gsize i = 0; i < config->n_rules; i++)
    {
      if (g_strcmp0 (config->rules[i].action, action) == 0)
        {
          g_free (config->rules[i].timeout);
          config->rules[i].timeout = g_strdup_printf ("%u", timeout_secs);
          return TRUE;
        }
    }

  config->rules = g_renew (CcHypridleRule, config->rules, config->n_rules + 1);
  config->rules[config->n_rules].timeout = g_strdup_printf ("%u", timeout_secs);
  config->rules[config->n_rules].action = g_strdup (action);
  config->n_rules++;

  return TRUE;
}

void
cc_hypridle_restart (void)
{
  g_spawn_command_line_async ("killall hypridle; hypridle &", NULL);
}
